// Generated by https://quicktype.io


export interface ClientesPorVendedorResponse {
    obtenerClientesPorVendedor: ObtenerClientesPorVendedor[];
}

export interface ObtenerClientesPorVendedor {
    vendedor: string;
    telefono: string;
    nombre:   string;
    id:       string;
    empresa:  string;
    email:    string;
    creado:   string;
    apellido: string;
}
