// Generated by https://quicktype.io

//! Se tiene que eliminar la proìedad data
// export interface RespuestaUsuarioNuevo {
//     data: Data;
// }

export interface RespuestaUsuarioNuevo {
    nuevoUsuario: NuevoUsuario;
}

export interface NuevoUsuario {
    apellido: string;
    creado:   string;
    email:    string;
    id:       string;
    nombre:   string;
}
